#ifndef REGISTRATIONSTATUS_H
#define REGISTRATIONSTATUS_H

enum class RegistrationStatus 
{
	CURRENTLY_DEREGISTERED,
	PENDING_REGISTRATION,
	CURRENTLY_REGISTERED,
	PENDING_DEREGISTRATION
};

#endif // REGISTRATIONSTATUS_H